// <auto-generated />
using System;
using GoldMetrics.GoldCheck.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldMetrics.GoldCheck.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615023135_AddConsumerTraceabilitySchema")]
    partial class AddConsumerTraceabilitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.Aggregates.JewelryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ScanCount")
                        .HasColumnType("int")
                        .HasColumnName("scan_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_jewelry_products");

                    b.ToTable("jewelry_products");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.Aggregates.TraceabilityJourney", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("JourneySummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("journey_summary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_traceability_journeys");

                    b.ToTable("traceability_journeys");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DownloadedByUserId")
                        .HasColumnType("longtext")
                        .HasColumnName("downloaded_by_user_id");

                    b.Property<string>("IncidentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("incident_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reports");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.Aggregates.JewelryProduct", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.ValueObjects.ConsumerId", "ConsumerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("consumer_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_products");

                            b1.ToTable("jewelry_products");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_products_jewelry_products_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.ValueObjects.ProductQRCode", "QRCode", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("q_r_code");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_products");

                            b1.ToTable("jewelry_products");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_products_jewelry_products_id");
                        });

                    b.Navigation("ConsumerId")
                        .IsRequired();

                    b.Navigation("QRCode")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.Aggregates.TraceabilityJourney", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.ValueObjects.ConsumerId", "ConsumerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("consumer_id");

                            b1.HasKey("Id")
                                .HasName("p_k_traceability_journeys");

                            b1.ToTable("traceability_journeys");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_traceability_journeys_traceability_journeys_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.ValueObjects.ProductQRCode", "ProductQRCode", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("product_q_r_code");

                            b1.HasKey("Id")
                                .HasName("p_k_traceability_journeys");

                            b1.ToTable("traceability_journeys");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_traceability_journeys_traceability_journeys_id");
                        });

                    b.Navigation("ConsumerId")
                        .IsRequired();

                    b.Navigation("ProductQRCode")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.HashedPassword", "HashedPassword", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("hashed_password");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.UserRole", "Role", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("role");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("username");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("HashedPassword")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Report", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.ReportFormat", "ReportFormat", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("report_format");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.ReportStatus", "ReportStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("report_status");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.SupervisorId", "SupervisorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("supervisor_id");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.Navigation("ReportFormat")
                        .IsRequired();

                    b.Navigation("ReportStatus")
                        .IsRequired();

                    b.Navigation("SupervisorId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
