// <auto-generated />
using System;
using GoldMetrics.GoldCheck.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldMetrics.GoldCheck.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620035051_AddIncidentManagementSchema")]
    partial class AddIncidentManagementSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.Aggregates.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset?>("ProductionEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("ProductionEnd");

                    b.Property<DateTimeOffset?>("ProductionStart")
                        .HasColumnType("datetime")
                        .HasColumnName("ProductionStart");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.AssetMaintenance.Domain.Model.Aggregates.Machinery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ComponentDischargeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DischargeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DischargedComponentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("MaintenanceScheduledAtHours")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MaintenanceScheduledAtHours");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OEM")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Machinery");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.Aggregates.HaulingCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DumpingPointName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("dumping_point_name");

                    b.Property<decimal?>("PayloadTons")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("payload_tons");

                    b.Property<string>("RouteProgress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("route_progress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_hauling_cycles");

                    b.ToTable("hauling_cycles");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.Aggregates.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEngineOn")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_engine_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_vehicles");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.Aggregates.SafetyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("SafetyRecord");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.Jewelry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_signed");

                    b.Property<string>("MaterialIdRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("material_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_jewelries");

                    b.ToTable("jewelries");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.JewelryMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CertificateIdRef")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("certificate_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("QRCodeValue")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("q_r_code");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_jewelry_materials");

                    b.ToTable("jewelry_materials");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.Aggregates.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("current_location");

                    b.Property<string>("DumpingPointName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("dumping_point_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_materials");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DownloadedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("downloaded_by_user_id");

                    b.Property<string>("IncidentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("incident_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reports");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Aggregates.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AccessGranted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AssignedFeatures")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("assigned_features");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RequestedDowngradePlan")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("UserSubscription");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserSubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.Aggregates.Material", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.ValueObjects.MaterialId", "MaterialId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("MaterialId");

                            b1.HasKey("Id");

                            b1.ToTable("Material");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.ValueObjects.RouteId", "RouteId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("RouteId");

                            b1.HasKey("Id");

                            b1.ToTable("Material");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.ValueObjects.RouteStatus", "RouteStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("RouteStatus");

                            b1.HasKey("Id");

                            b1.ToTable("Material");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.ValueObjects.SupervisorId", "SupervisorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("SupervisorId");

                            b1.HasKey("Id");

                            b1.ToTable("Material");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.ValueObjects.UserId", "UserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("UserId");

                            b1.HasKey("Id");

                            b1.ToTable("Material");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("MaterialId")
                        .IsRequired();

                    b.Navigation("RouteId")
                        .IsRequired();

                    b.Navigation("RouteStatus")
                        .IsRequired();

                    b.Navigation("SupervisorId")
                        .IsRequired();

                    b.Navigation("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.AssetMaintenance.Domain.Model.Aggregates.Machinery", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.AssetMaintenance.Domain.Model.ValueObjects.EngineHours", "EngineHours", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<decimal>("Hours")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("EngineHours");

                            b1.HasKey("Id");

                            b1.ToTable("Machinery");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.AssetMaintenance.Domain.Model.ValueObjects.MachineryId", "MachineryId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("MachineryId");

                            b1.HasKey("Id");

                            b1.ToTable("Machinery");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.AssetMaintenance.Domain.Model.ValueObjects.MaintenanceStatus", "MaintenanceStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("MaintenanceStatus");

                            b1.HasKey("Id");

                            b1.ToTable("Machinery");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("EngineHours")
                        .IsRequired();

                    b.Navigation("MachineryId")
                        .IsRequired();

                    b.Navigation("MaintenanceStatus")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.Aggregates.HaulingCycle", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.ValueObjects.VehicleId", "VehicleId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("vehicle_id");

                            b1.HasKey("Id")
                                .HasName("p_k_hauling_cycles");

                            b1.ToTable("hauling_cycles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_hauling_cycles_hauling_cycles_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.ValueObjects.LoadingPoint", "LoadingPoint", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("loading_point_name");

                            b1.HasKey("Id")
                                .HasName("p_k_hauling_cycles");

                            b1.ToTable("hauling_cycles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_hauling_cycles_hauling_cycles_id");
                        });

                    b.Navigation("LoadingPoint")
                        .IsRequired();

                    b.Navigation("VehicleId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.Aggregates.Vehicle", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.ValueObjects.VehicleId", "VehicleId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("vehicle_id");

                            b1.HasKey("Id")
                                .HasName("p_k_vehicles");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_vehicles_vehicles_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.ValueObjects.OperatorId", "OperatorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("operator_id");

                            b1.HasKey("Id")
                                .HasName("p_k_vehicles");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_vehicles_vehicles_id");
                        });

                    b.Navigation("OperatorId")
                        .IsRequired();

                    b.Navigation("VehicleId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.HashedPassword", "HashedPassword", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("hashed_password");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.UserRole", "Role", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("role");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("username");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("HashedPassword")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.Aggregates.SafetyRecord", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.ValueObjects.AssetId", "AssetId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("AssetId");

                            b1.HasKey("Id");

                            b1.ToTable("SafetyRecord");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.ValueObjects.IncidentType", "IncidentType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("IncidentType");

                            b1.HasKey("Id");

                            b1.ToTable("SafetyRecord");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.ValueObjects.OperatorId", "OperatorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("OperatorId");

                            b1.HasKey("Id");

                            b1.ToTable("SafetyRecord");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.ValueObjects.RiskLevel", "RiskLevel", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("RiskLevel");

                            b1.HasKey("Id");

                            b1.ToTable("SafetyRecord");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("AssetId")
                        .IsRequired();

                    b.Navigation("IncidentType")
                        .IsRequired();

                    b.Navigation("OperatorId")
                        .IsRequired();

                    b.Navigation("RiskLevel")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.Jewelry", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.JewelerId", "JewelerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("jeweler_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelries");

                            b1.ToTable("jewelries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelries_jewelries_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.CertificateId", "CertificateId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("certificate_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelries");

                            b1.ToTable("jewelries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelries_jewelries_id");
                        });

                    b.Navigation("CertificateId")
                        .IsRequired();

                    b.Navigation("JewelerId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.JewelryMaterial", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.JewelerId", "JewelerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("jeweler_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_materials");

                            b1.ToTable("jewelry_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_materials_jewelry_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.MaterialId", "MaterialId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("material_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_materials");

                            b1.ToTable("jewelry_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_materials_jewelry_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.MaterialStatus", "Status", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("status");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_materials");

                            b1.ToTable("jewelry_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_materials_jewelry_materials_id");
                        });

                    b.Navigation("JewelerId")
                        .IsRequired();

                    b.Navigation("MaterialId")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.Aggregates.Material", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.ValueObjects.MaterialBatchId", "BatchId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("batch_id");

                            b1.HasKey("Id")
                                .HasName("p_k_materials");

                            b1.ToTable("materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_materials_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.ValueObjects.MineralType", "MineralType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("mineral_type");

                            b1.HasKey("Id")
                                .HasName("p_k_materials");

                            b1.ToTable("materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_materials_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.ValueObjects.Payload", "Payload", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Tons")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("payload_tons");

                            b1.HasKey("Id")
                                .HasName("p_k_materials");

                            b1.ToTable("materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_materials_materials_id");
                        });

                    b.Navigation("BatchId")
                        .IsRequired();

                    b.Navigation("MineralType")
                        .IsRequired();

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.NotificationStatus", "NotificationStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("notification_status");

                            b1.HasKey("Id")
                                .HasName("p_k_notifications");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_notifications_notifications_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.NotificationType", "NotificationType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("notification_type");

                            b1.HasKey("Id")
                                .HasName("p_k_notifications");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_notifications_notifications_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.RecipientId", "RecipientId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("recipient_id");

                            b1.HasKey("Id")
                                .HasName("p_k_notifications");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_notifications_notifications_id");
                        });

                    b.Navigation("NotificationStatus")
                        .IsRequired();

                    b.Navigation("NotificationType")
                        .IsRequired();

                    b.Navigation("RecipientId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Report", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.ReportFormat", "ReportFormat", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("report_format");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.ReportStatus", "ReportStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("report_status");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.SupervisorId", "SupervisorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("supervisor_id");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.Navigation("ReportFormat")
                        .IsRequired();

                    b.Navigation("ReportStatus")
                        .IsRequired();

                    b.Navigation("SupervisorId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Aggregates.UserSubscription", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.BillingCycle", "BillingCycle", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("billing_cycle");

                            b1.HasKey("Id");

                            b1.ToTable("UserSubscription");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.PlanType", "PlanType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("plan_type");

                            b1.HasKey("Id");

                            b1.ToTable("UserSubscription");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.SubscriptionStatus", "SubscriptionStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("subscription_status");

                            b1.HasKey("Id");

                            b1.ToTable("UserSubscription");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.UserId", "UserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("user_id");

                            b1.HasKey("Id");

                            b1.ToTable("UserSubscription");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("BillingCycle")
                        .IsRequired();

                    b.Navigation("PlanType")
                        .IsRequired();

                    b.Navigation("SubscriptionStatus")
                        .IsRequired();

                    b.Navigation("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Entities.Invoice", b =>
                {
                    b.HasOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Aggregates.UserSubscription", null)
                        .WithMany("Invoices")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.Amount", "Amount", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.HasKey("Id");

                            b1.ToTable("Invoice");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.InvoiceId", "InvoiceId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("invoice_id");

                            b1.HasKey("Id");

                            b1.ToTable("Invoice");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("InvoiceId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Aggregates.UserSubscription", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
