// <auto-generated />
using System;
using GoldMetrics.GoldCheck.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldMetrics.GoldCheck.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620224824_AddMonitoringTelemetrySchema")]
    partial class AddMonitoringTelemetrySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.Aggregates.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ProductionEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("production_end");

                    b.Property<DateTimeOffset?>("ProductionStart")
                        .HasColumnType("datetime")
                        .HasColumnName("production_start");

                    b.Property<decimal?>("ProductionTons")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("production_tons");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_analytics_materials");

                    b.ToTable("analytics_materials", (string)null);
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.AssetMaintenance.Domain.Model.Aggregates.Machinery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ComponentDischargeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("component_discharge_reason");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DischargeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("discharge_reason");

                    b.Property<string>("DischargedComponentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("discharged_component_id");

                    b.Property<decimal?>("MaintenanceScheduledAtHours")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("maintenance_scheduled_at_hours");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("model");

                    b.Property<string>("OEM")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("o_e_m");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_machineries");

                    b.ToTable("machineries");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.Aggregates.JewelryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CertificateIdRef")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("certificate_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("ScanCount")
                        .HasColumnType("int")
                        .HasColumnName("scan_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_jewelry_products");

                    b.ToTable("jewelry_products");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.Aggregates.TraceabilityJourney", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("JourneySummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("journey_summary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_traceability_journeys");

                    b.ToTable("traceability_journeys");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.Aggregates.HaulingCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DumpingPointName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("dumping_point_name");

                    b.Property<decimal?>("PayloadTons")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("payload_tons");

                    b.Property<string>("RouteProgress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("route_progress");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_hauling_cycles");

                    b.ToTable("hauling_cycles");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.Aggregates.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEngineOn")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_engine_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_vehicles");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.Aggregates.SafetyRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_safety_records");

                    b.ToTable("safety_records");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.Jewelry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_signed");

                    b.Property<string>("MaterialIdRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("material_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_jewelries");

                    b.ToTable("jewelries");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.JewelryMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CertificateIdRef")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("certificate_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("QRCodeValue")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("q_r_code");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_jewelry_materials");

                    b.ToTable("jewelry_materials");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.Aggregates.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("current_location");

                    b.Property<string>("DumpingPointName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("dumping_point_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_material_operations_materials");

                    b.ToTable("material_operations_materials", (string)null);
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.CommunicationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AnomalyDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("anomaly_description");

                    b.Property<string>("AnomalyProtocol")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("anomaly_protocol");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("LastAnalysedProtocol")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_analysed_protocol");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_communication_channels");

                    b.ToTable("communication_channels");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.GNSSStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("RestartCount")
                        .HasColumnType("int")
                        .HasColumnName("restart_count");

                    b.Property<string>("RestartReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("restart_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_gnss_statuses");

                    b.ToTable("gnss_statuses", (string)null);
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.PressureReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("AbsoluteEngineOilBar")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("absolute_engine_oil_bar");

                    b.Property<string>("AnomalyDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("anomaly_description");

                    b.Property<string>("AnomalyPressureType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("anomaly_pressure_type");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("OilFilterBar")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("oil_filter_bar");

                    b.Property<decimal?>("OilFilterDifferenceBar")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("oil_filter_difference_bar");

                    b.Property<decimal?>("OilPanBar")
                        .HasColumnType("decimal(8,4)")
                        .HasColumnName("oil_pan_bar");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_pressure_readings");

                    b.ToTable("pressure_readings");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.SpeedReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentSpeedKmPerHour")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("current_speed_km_per_hour");

                    b.Property<bool>("IsViolation")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_violation");

                    b.Property<decimal?>("SpeedLimitKmPerHour")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("speed_limit_km_per_hour");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("ViolationDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("violation_description");

                    b.HasKey("Id")
                        .HasName("p_k_speed_readings");

                    b.ToTable("speed_readings");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.TelemetryData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_validated");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("raw_data");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TelemetryDataId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("telemetry_data_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_telemetry_data");

                    b.ToTable("telemetry_data", (string)null);
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.TemperatureReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("AnomalyCelsius")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("anomaly_celsius");

                    b.Property<string>("AnomalyDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("anomaly_description");

                    b.Property<string>("AnomalyType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("anomaly_type");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("CylinderNumber")
                        .HasColumnType("int")
                        .HasColumnName("cylinder_number");

                    b.Property<decimal?>("ExhaustCelsius")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("exhaust_celsius");

                    b.Property<decimal?>("ExhaustLimitCelsius")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("exhaust_limit_celsius");

                    b.Property<decimal?>("FuelCelsius")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("fuel_celsius");

                    b.Property<decimal?>("OilCelsius")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("oil_celsius");

                    b.Property<decimal?>("RefrigerantCelsius")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("refrigerant_celsius");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_temperature_readings");

                    b.ToTable("temperature_readings");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DownloadedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("downloaded_by_user_id");

                    b.Property<string>("IncidentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("incident_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reports");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Aggregates.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("AccessGranted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("access_granted");

                    b.Property<string>("AssignedFeatures")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("assigned_features");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("RequestedDowngradePlan")
                        .HasColumnType("longtext")
                        .HasColumnName("requested_downgrade_plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_user_subscriptions");

                    b.ToTable("user_subscriptions");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("UserSubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("user_subscription_id");

                    b.HasKey("Id")
                        .HasName("p_k_invoices");

                    b.HasIndex("UserSubscriptionId")
                        .HasDatabaseName("i_x_invoices_user_subscription_id");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.Aggregates.Material", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.ValueObjects.MaterialId", "MaterialId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("material_id");

                            b1.HasKey("Id")
                                .HasName("p_k_analytics_materials");

                            b1.ToTable("analytics_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_analytics_materials_analytics_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.ValueObjects.RouteId", "RouteId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("route_id");

                            b1.HasKey("Id")
                                .HasName("p_k_analytics_materials");

                            b1.ToTable("analytics_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_analytics_materials_analytics_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.ValueObjects.RouteStatus", "RouteStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("route_status");

                            b1.HasKey("Id")
                                .HasName("p_k_analytics_materials");

                            b1.ToTable("analytics_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_analytics_materials_analytics_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.ValueObjects.SupervisorId", "SupervisorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("supervisor_id");

                            b1.HasKey("Id")
                                .HasName("p_k_analytics_materials");

                            b1.ToTable("analytics_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_analytics_materials_analytics_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Analytics.Domain.Model.ValueObjects.UserId", "UserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("user_id");

                            b1.HasKey("Id")
                                .HasName("p_k_analytics_materials");

                            b1.ToTable("analytics_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_analytics_materials_analytics_materials_id");
                        });

                    b.Navigation("MaterialId")
                        .IsRequired();

                    b.Navigation("RouteId")
                        .IsRequired();

                    b.Navigation("RouteStatus")
                        .IsRequired();

                    b.Navigation("SupervisorId")
                        .IsRequired();

                    b.Navigation("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.AssetMaintenance.Domain.Model.Aggregates.Machinery", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.AssetMaintenance.Domain.Model.ValueObjects.EngineHours", "EngineHours", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Hours")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("engine_hours");

                            b1.HasKey("Id")
                                .HasName("p_k_machineries");

                            b1.ToTable("machineries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_machineries_machineries_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.AssetMaintenance.Domain.Model.ValueObjects.MachineryId", "MachineryId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("machinery_id");

                            b1.HasKey("Id")
                                .HasName("p_k_machineries");

                            b1.ToTable("machineries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_machineries_machineries_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.AssetMaintenance.Domain.Model.ValueObjects.MaintenanceStatus", "MaintenanceStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("maintenance_status");

                            b1.HasKey("Id")
                                .HasName("p_k_machineries");

                            b1.ToTable("machineries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_machineries_machineries_id");
                        });

                    b.Navigation("EngineHours")
                        .IsRequired();

                    b.Navigation("MachineryId")
                        .IsRequired();

                    b.Navigation("MaintenanceStatus")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.Aggregates.JewelryProduct", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.ValueObjects.ConsumerId", "ConsumerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("consumer_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_products");

                            b1.ToTable("jewelry_products");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_products_jewelry_products_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.ValueObjects.ProductQRCode", "QRCode", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("q_r_code");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_products");

                            b1.ToTable("jewelry_products");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_products_jewelry_products_id");
                        });

                    b.Navigation("ConsumerId")
                        .IsRequired();

                    b.Navigation("QRCode")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.Aggregates.TraceabilityJourney", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.ValueObjects.ConsumerId", "ConsumerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("consumer_id");

                            b1.HasKey("Id")
                                .HasName("p_k_traceability_journeys");

                            b1.ToTable("traceability_journeys");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_traceability_journeys_traceability_journeys_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ConsumerTraceability.Domain.Model.ValueObjects.ProductQRCode", "ProductQRCode", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("product_q_r_code");

                            b1.HasKey("Id")
                                .HasName("p_k_traceability_journeys");

                            b1.ToTable("traceability_journeys");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_traceability_journeys_traceability_journeys_id");
                        });

                    b.Navigation("ConsumerId")
                        .IsRequired();

                    b.Navigation("ProductQRCode")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.Aggregates.HaulingCycle", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.ValueObjects.VehicleId", "VehicleId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("vehicle_id");

                            b1.HasKey("Id")
                                .HasName("p_k_hauling_cycles");

                            b1.ToTable("hauling_cycles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_hauling_cycles_hauling_cycles_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.ValueObjects.LoadingPoint", "LoadingPoint", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("loading_point_name");

                            b1.HasKey("Id")
                                .HasName("p_k_hauling_cycles");

                            b1.ToTable("hauling_cycles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_hauling_cycles_hauling_cycles_id");
                        });

                    b.Navigation("LoadingPoint")
                        .IsRequired();

                    b.Navigation("VehicleId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.Aggregates.Vehicle", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.ValueObjects.VehicleId", "VehicleId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("vehicle_id");

                            b1.HasKey("Id")
                                .HasName("p_k_vehicles");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_vehicles_vehicles_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.FleetOperations.Domain.Model.ValueObjects.OperatorId", "OperatorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("operator_id");

                            b1.HasKey("Id")
                                .HasName("p_k_vehicles");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_vehicles_vehicles_id");
                        });

                    b.Navigation("OperatorId")
                        .IsRequired();

                    b.Navigation("VehicleId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.HashedPassword", "HashedPassword", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("hashed_password");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.UserRole", "Role", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("role");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("username");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("HashedPassword")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.Aggregates.SafetyRecord", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.ValueObjects.AssetId", "AssetId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("asset_id");

                            b1.HasKey("Id")
                                .HasName("p_k_safety_records");

                            b1.ToTable("safety_records");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_safety_records_safety_records_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.ValueObjects.IncidentType", "IncidentType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("incident_type");

                            b1.HasKey("Id")
                                .HasName("p_k_safety_records");

                            b1.ToTable("safety_records");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_safety_records_safety_records_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.ValueObjects.OperatorId", "OperatorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("operator_id");

                            b1.HasKey("Id")
                                .HasName("p_k_safety_records");

                            b1.ToTable("safety_records");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_safety_records_safety_records_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.IncidentManagement.Domain.Model.ValueObjects.RiskLevel", "RiskLevel", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("risk_level");

                            b1.HasKey("Id")
                                .HasName("p_k_safety_records");

                            b1.ToTable("safety_records");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_safety_records_safety_records_id");
                        });

                    b.Navigation("AssetId")
                        .IsRequired();

                    b.Navigation("IncidentType")
                        .IsRequired();

                    b.Navigation("OperatorId")
                        .IsRequired();

                    b.Navigation("RiskLevel")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.Jewelry", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.JewelerId", "JewelerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("jeweler_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelries");

                            b1.ToTable("jewelries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelries_jewelries_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.CertificateId", "CertificateId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("certificate_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelries");

                            b1.ToTable("jewelries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelries_jewelries_id");
                        });

                    b.Navigation("CertificateId")
                        .IsRequired();

                    b.Navigation("JewelerId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.JewelryMaterial", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.JewelerId", "JewelerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("jeweler_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_materials");

                            b1.ToTable("jewelry_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_materials_jewelry_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.MaterialId", "MaterialId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("material_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_materials");

                            b1.ToTable("jewelry_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_materials_jewelry_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.MaterialStatus", "Status", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("status");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_materials");

                            b1.ToTable("jewelry_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_materials_jewelry_materials_id");
                        });

                    b.Navigation("JewelerId")
                        .IsRequired();

                    b.Navigation("MaterialId")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.Aggregates.Material", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.ValueObjects.MaterialBatchId", "BatchId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("batch_id");

                            b1.HasKey("Id")
                                .HasName("p_k_material_operations_materials");

                            b1.ToTable("material_operations_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_material_operations_materials_material_operations_materials_~");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.ValueObjects.MineralType", "MineralType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("mineral_type");

                            b1.HasKey("Id")
                                .HasName("p_k_material_operations_materials");

                            b1.ToTable("material_operations_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_material_operations_materials_material_operations_materials_~");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.ValueObjects.Payload", "Payload", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Tons")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("payload_tons");

                            b1.HasKey("Id")
                                .HasName("p_k_material_operations_materials");

                            b1.ToTable("material_operations_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_material_operations_materials_material_operations_materials_~");
                        });

                    b.Navigation("BatchId")
                        .IsRequired();

                    b.Navigation("MineralType")
                        .IsRequired();

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.CommunicationChannel", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.ValueObjects.AssetId", "AssetId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("asset_id");

                            b1.HasKey("Id")
                                .HasName("p_k_communication_channels");

                            b1.ToTable("communication_channels");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_communication_channels_communication_channels_id");
                        });

                    b.Navigation("AssetId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.GNSSStatus", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.ValueObjects.AssetId", "AssetId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("asset_id");

                            b1.HasKey("Id")
                                .HasName("p_k_gnss_statuses");

                            b1.ToTable("gnss_statuses");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_gnss_statuses_gnss_statuses_id");
                        });

                    b.Navigation("AssetId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.PressureReading", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.ValueObjects.AssetId", "AssetId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("asset_id");

                            b1.HasKey("Id")
                                .HasName("p_k_pressure_readings");

                            b1.ToTable("pressure_readings");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_pressure_readings_pressure_readings_id");
                        });

                    b.Navigation("AssetId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.SpeedReading", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.ValueObjects.AssetId", "AssetId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("asset_id");

                            b1.HasKey("Id")
                                .HasName("p_k_speed_readings");

                            b1.ToTable("speed_readings");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_speed_readings_speed_readings_id");
                        });

                    b.Navigation("AssetId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.TelemetryData", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.ValueObjects.AssetId", "AssetId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("asset_id");

                            b1.HasKey("Id")
                                .HasName("p_k_telemetry_data");

                            b1.ToTable("telemetry_data");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_telemetry_data_telemetry_data_id");
                        });

                    b.Navigation("AssetId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.Aggregates.TemperatureReading", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MonitoringTelemetry.Domain.Model.ValueObjects.AssetId", "AssetId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("asset_id");

                            b1.HasKey("Id")
                                .HasName("p_k_temperature_readings");

                            b1.ToTable("temperature_readings");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_temperature_readings_temperature_readings_id");
                        });

                    b.Navigation("AssetId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.NotificationStatus", "NotificationStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("notification_status");

                            b1.HasKey("Id")
                                .HasName("p_k_notifications");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_notifications_notifications_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.NotificationType", "NotificationType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("notification_type");

                            b1.HasKey("Id")
                                .HasName("p_k_notifications");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_notifications_notifications_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.RecipientId", "RecipientId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("recipient_id");

                            b1.HasKey("Id")
                                .HasName("p_k_notifications");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_notifications_notifications_id");
                        });

                    b.Navigation("NotificationStatus")
                        .IsRequired();

                    b.Navigation("NotificationType")
                        .IsRequired();

                    b.Navigation("RecipientId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Report", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.ReportFormat", "ReportFormat", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("report_format");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.ReportStatus", "ReportStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("report_status");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.SupervisorId", "SupervisorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("supervisor_id");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.Navigation("ReportFormat")
                        .IsRequired();

                    b.Navigation("ReportStatus")
                        .IsRequired();

                    b.Navigation("SupervisorId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Aggregates.UserSubscription", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.BillingCycle", "BillingCycle", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("billing_cycle");

                            b1.HasKey("Id")
                                .HasName("p_k_user_subscriptions");

                            b1.ToTable("user_subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_user_subscriptions_user_subscriptions_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.PlanType", "PlanType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("plan_type");

                            b1.HasKey("Id")
                                .HasName("p_k_user_subscriptions");

                            b1.ToTable("user_subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_user_subscriptions_user_subscriptions_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.SubscriptionStatus", "SubscriptionStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("subscription_status");

                            b1.HasKey("Id")
                                .HasName("p_k_user_subscriptions");

                            b1.ToTable("user_subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_user_subscriptions_user_subscriptions_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.UserId", "UserId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("user_id");

                            b1.HasKey("Id")
                                .HasName("p_k_user_subscriptions");

                            b1.ToTable("user_subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_user_subscriptions_user_subscriptions_id");
                        });

                    b.Navigation("BillingCycle")
                        .IsRequired();

                    b.Navigation("PlanType")
                        .IsRequired();

                    b.Navigation("SubscriptionStatus")
                        .IsRequired();

                    b.Navigation("UserId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Entities.Invoice", b =>
                {
                    b.HasOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Aggregates.UserSubscription", null)
                        .WithMany("Invoices")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_invoices_user_subscriptions_user_subscription_id");

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.Amount", "Amount", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.HasKey("Id")
                                .HasName("p_k_invoices");

                            b1.ToTable("invoices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_invoices_invoices_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.ValueObjects.InvoiceId", "InvoiceId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("invoice_id");

                            b1.HasKey("Id")
                                .HasName("p_k_invoices");

                            b1.ToTable("invoices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_invoices_invoices_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("InvoiceId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.SubscriptionsAndBilling.Domain.Model.Aggregates.UserSubscription", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
