// <auto-generated />
using System;
using GoldMetrics.GoldCheck.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldMetrics.GoldCheck.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616014423_AddJewelryCertificatesSchema")]
    partial class AddJewelryCertificatesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.Jewelry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_signed");

                    b.Property<string>("MaterialIdRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("material_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_jewelries");

                    b.ToTable("jewelries");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.JewelryMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CertificateIdRef")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("certificate_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("QRCodeValue")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("q_r_code");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_jewelry_materials");

                    b.ToTable("jewelry_materials");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.Aggregates.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("current_location");

                    b.Property<string>("DumpingPointName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("dumping_point_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_materials");

                    b.ToTable("materials");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DownloadedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("downloaded_by_user_id");

                    b.Property<string>("IncidentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("incident_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_reports");

                    b.ToTable("reports");
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.HashedPassword", "HashedPassword", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("hashed_password");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.UserRole", "Role", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("role");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.Iam.Domain.Model.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("username");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("HashedPassword")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.Jewelry", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.JewelerId", "JewelerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("jeweler_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelries");

                            b1.ToTable("jewelries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelries_jewelries_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.CertificateId", "CertificateId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("certificate_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelries");

                            b1.ToTable("jewelries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelries_jewelries_id");
                        });

                    b.Navigation("CertificateId")
                        .IsRequired();

                    b.Navigation("JewelerId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.Aggregates.JewelryMaterial", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.JewelerId", "JewelerId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("jeweler_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_materials");

                            b1.ToTable("jewelry_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_materials_jewelry_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.MaterialId", "MaterialId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("material_id");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_materials");

                            b1.ToTable("jewelry_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_materials_jewelry_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.JewelryInventory.Domain.Model.ValueObjects.MaterialStatus", "Status", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("status");

                            b1.HasKey("Id")
                                .HasName("p_k_jewelry_materials");

                            b1.ToTable("jewelry_materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_jewelry_materials_jewelry_materials_id");
                        });

                    b.Navigation("JewelerId")
                        .IsRequired();

                    b.Navigation("MaterialId")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.Aggregates.Material", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.ValueObjects.MaterialBatchId", "BatchId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("batch_id");

                            b1.HasKey("Id")
                                .HasName("p_k_materials");

                            b1.ToTable("materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_materials_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.ValueObjects.MineralType", "MineralType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("mineral_type");

                            b1.HasKey("Id")
                                .HasName("p_k_materials");

                            b1.ToTable("materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_materials_materials_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.MaterialOperations.Domain.Model.ValueObjects.Payload", "Payload", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Tons")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("payload_tons");

                            b1.HasKey("Id")
                                .HasName("p_k_materials");

                            b1.ToTable("materials");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_materials_materials_id");
                        });

                    b.Navigation("BatchId")
                        .IsRequired();

                    b.Navigation("MineralType")
                        .IsRequired();

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.NotificationStatus", "NotificationStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("notification_status");

                            b1.HasKey("Id")
                                .HasName("p_k_notifications");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_notifications_notifications_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.NotificationType", "NotificationType", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("notification_type");

                            b1.HasKey("Id")
                                .HasName("p_k_notifications");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_notifications_notifications_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.RecipientId", "RecipientId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("recipient_id");

                            b1.HasKey("Id")
                                .HasName("p_k_notifications");

                            b1.ToTable("notifications");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_notifications_notifications_id");
                        });

                    b.Navigation("NotificationStatus")
                        .IsRequired();

                    b.Navigation("NotificationType")
                        .IsRequired();

                    b.Navigation("RecipientId")
                        .IsRequired();
                });

            modelBuilder.Entity("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.Aggregates.Report", b =>
                {
                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.ReportFormat", "ReportFormat", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("report_format");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.ReportStatus", "ReportStatus", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("report_status");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.OwnsOne("GoldMetrics.GoldCheck.Platform.ReportingNotifications.Domain.Model.ValueObjects.SupervisorId", "SupervisorId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("supervisor_id");

                            b1.HasKey("Id")
                                .HasName("p_k_reports");

                            b1.ToTable("reports");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_reports_reports_id");
                        });

                    b.Navigation("ReportFormat")
                        .IsRequired();

                    b.Navigation("ReportStatus")
                        .IsRequired();

                    b.Navigation("SupervisorId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
